jobs:
- job: MacOS_py_Wheels
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'

  steps:
    - task: UsePythonVersion@0
      displayName: 'Choosing Python Version'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        sudo python -m pip install numpy
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        ./build.sh --skip_submodule_sync --parallel --build_wheel --use_mkldnn
      displayName: 'Command Line Script'

    - task: CopyFiles@2
      displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/dist/onnxruntime-*.whl'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ONNXRuntime python wheel'
      inputs:
        ArtifactName: onnxruntime

    - script: 'sudo rm -rf $(Agent.BuildDirectory)'
      displayName: 'Clean build folders/files'
      condition: always()
